# Generated by Django 2.0.4 on 2018-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20180913_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='firt_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='regno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
