# Generated by Django 2.0.4 on 2018-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20181009_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='course',
            field=models.CharField(default='', max_length=20),
        ),
    ]
